# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: CompetitorAnalyzer_Environment 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY  }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Remove old files
      run: sudo rm -r /var/www/competitor-analyzer
    - name: Copy files
      run: sudo cp -r -f /etc/actions-runner_competitor-analyzer/_work/competitor-analyzer/competitor-analyzer/dist/competitor-analyzer/. /var/www/competitor-analyzer
